### ISSUE TITLE
Sidecar Config

### ISSUE THREAD

**Issue by tdgeery** [runatlantis/helm-charts#92] opened 2021-10-12 18:21 UTC
Wondering if its possible to add a sidecar config to the StatefulSet in order to run a task to remove plugin-cache periodically. 
Recently we had our atlantis instance run out of disk space.

In this comment they added a sidecar do to this once daily:
https://github.com/runatlantis/atlantis/issues/1030#issuecomment-784207636

**Comment by nitrocode** [comment] 2022-11-05 22:07
Thanks for adding this issue. I think this is a duplicate of https://github.com/runatlantis/helm-charts/issues/28 so let's close this and keep the conversation there until this gets implemented.

Also, please feel free to submit PRs. We are happy to review!

**Closed by nitrocode** 2022-11-05 22:07 UTC
