### ISSUE TITLE
Default uuid wrong if using debian image

### ISSUE THREAD

**Issue by endriu0** [runatlantis/helm-charts#305] opened 2023-06-26 13:38 UTC
So with the introduction of debian based image the default uuid is now wrong :
 
https://github.com/runatlantis/helm-charts/blob/3aa2c78167587ba1db03c52b21d62a098c94596d/charts/atlantis/values.yaml#L232

uuid 100 on debian is _apt vs uuid 100 on alpine being atlantis.

To be able to do things normally debian needs uuid changed to 1000.

Not sure what would be the best way to make the chart automatically guess which it should use tbh - Ive seen some projects try to guess based on image name but this seems very finicky. 

I guess we can just add a comment about this gotcha to the chart and also add an entry in the actual atlantis documentation.

**Comment by GMartinez-Sisti** [comment] 2023-07-09 11:28
Duplicate of https://github.com/runatlantis/helm-charts/issues/306, although this was created first https://github.com/runatlantis/helm-charts/issues/306 already has some discussion going on.

**Closed** 2024-05-04 11:39 UTC
