### ISSUE TITLE
Support helm chart for fargate nodes for EKS

### ISSUE THREAD

**Issue by sdwerwed** [runatlantis/helm-charts#40] opened 2021-03-14 06:10 UTC
Hello, PV need 2 values in addition to work with fargate nodes, I can create PR for updating the helm template if you can give me some direction. 

```
csi:
  driver: efs.csi.aws.com
  volumeHandle: fs-xxxxx
```
```
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-xxxxx
  storageClassName: efs-sc
  volumeMode: Filesystem
  ```

**Comment by joncolby** [comment] 2021-03-15 21:14
I also encountered this issue, trying to use this chart on AWS Fargate.   The `volumeClaimTemplates` needs to have more template options.   @sdwerwed -  did you test the configuration as you provided?   i intend test this also in the next day or so.   I would also be willing to create a PR.

**Comment by sdwerwed** [comment] 2021-03-16 08:42
The AWS does not currently support dynamic provisioning for now for Fargate, but if you install the master branch CSI driver it should work, maybe it will get released soon. 

Follow carefully the installation steps and then see the examples.
https://github.com/kubernetes-sigs/aws-efs-csi-driver
https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html

**Comment by joncolby** [comment] 2021-03-16 14:35
> The AWS does not currently support dynamic provisioning for now for Fargate, but if you install the master branch CSI driver it should work, maybe it will get released soon.
> 
but will the install CSI driver be used by fargate?  I thought fargate would be a whole independent layer with its own CSI drivers and volume creation mechanisms.   Did this work for you?

Anyway,  I did get an EFS volume to mount with the Atlantis chart by pre-creating the PVC and EFS FS and mounts.   I know it's a bit hacky.   but it buys me time until EKS/fargate/CSI catches up.

thanks for the feedback @sdwerwed  !

**Comment by sdwerwed** [comment] 2021-03-19 13:29
I tested the dynamic efs provisioning using the master branch (development) and it worked for EC2 nodes, I did not test fargate node. 

On the aws docs it says: 
> Deploy the Amazon EFS CSI driver using the command that corresponds with the Region that your cluster is in. If your cluster contains nodes (it can also include AWS Fargate pods), then deploy the driver with the following command.

**Comment by nitrocode** [comment] 2022-12-29 01:29
This seems like a duplicate of https://github.com/runatlantis/helm-charts/issues/22

**Comment by nitrocode** [comment] 2022-12-30 16:05
Closing to consolidate discussion in the original ticket. I added a comment in #22 to see if we can get it working. Please try it out and post results there if you get a chance.

**Closed by nitrocode** 2022-12-30 16:05 UTC
